### ISSUE TITLE
Support passing flexmark extension options

### ISSUE THREAD

**Issue by x12a1f** [mnlipp/jdrupes-mdoclet#10]
Hi,

I could not find a way to pass flexmark extension options. 

For example, on the tables extension I would like to configure the CLASS_NAME option as described in https://github.com/vsch/flexmark-java/wiki/Tables-Extension#parsing-details

Is this possible?
Thanks.

**Comment by mnlipp** [comment]
Hi,

forwarding arguments to the markdown processor is described [here](https://mnlipp.github.io/jdrupes-mdoclet/javadoc/#configuring-the-markdown-processor). If this does not work for you, I'd need an example of how the CLASS_NAME option is passed to flexmark when flexmark is used independently from the doclet.

**Comment by x12a1f** [comment]
I saw the '-M' option to pass arguments to the markdown processor, however, the flexmark processor only supports `--parser-profile`, `--clear-extensions` and `--extension`

I would like to add options to `flexmarkOpts` in:

https://github.com/mnlipp/jdrupes-mdoclet/blob/8c7c3cba671c13c93ca0d951a417d9bee9ef61ad/mdoclet/src/org/jdrupes/mdoclet/processors/FlexmarkProcessor.java#L147

for example adding the following option:

```java
flexmarkOpts.set(com.vladsch.flexmark.ext.table.TablesExtension.CLASS_NAME, "fancytable");
```

perhaps by adding a new -M option to FlexmarkProcessor which can be used as:

`-M --option=com.vladsch.flexmark.ext.table.TablesExtension.CLASS_NAME=fancytable`

At least, this is my understanding on how to pass flexmark extension options.

See also the flexmark example: 

https://github.com/vsch/flexmark-java/blob/8a881b73109a287b5f202e2e1fc9f9c497d5eecf/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/BasicSample.java#L16

**Comment by x12a1f** [comment]
If passing options like this is not possible yet and the proposed solution seems ok I can create a PR if you want.

**Comment by mnlipp** [comment]
Did you try to pass 

`-M --extension=com.vladsch.flexmark.ext.table.TablesExtension.CLASS_NAME=fancytable`

to mdoclet?

**Comment by mnlipp** [comment]
Closed because no more information was supplied.

**Comment by x12a1f** [comment]
Sorry, somehow I did not notice your message of Jun 29. I don't recall if the suggestion works or not. I think we found another solution.
