### ISSUE TITLE
It will be nice to have an example with Maven and Java 11.

### ISSUE THREAD

**Issue by javadev** [mnlipp/jdrupes-mdoclet#11]
Dear sir,

Please send me an example with pom.xml file.

**Comment by mnlipp** [comment]
See the [documentation](https://mnlipp.github.io/jdrupes-mdoclet/javadoc/#maven).

**Comment by javadev** [comment]
Thank you for the link.

Please send me an example with pom.xml file.

**Comment by mnlipp** [comment]
I'm afraid you didn't get the meaning of the link. I don't like maven, I don't use it, and I will (hopefully) never have to use it. If you wonder why, [here](https://web.archive.org/web/20190427072827/https://nealford.com/memeagora/2013/01/22/why_everyone_eventually_hates_maven.html) is a good explanation.

Therefore if you want to use mdoclet with maven, you'll have to find your own way how to do this. Feel free to document your solution for the sake of others. But I won't support this endeavor, I recommend to use gradle.

**Comment by rmuller** [comment]
This plugin can be used with maven without any issues, just add the following to your pom:

      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        
        <version>3.4.1</version>
        <configuration>
          ... your configuration options here
          <useStandardDocletOptions>true</useStandardDocletOptions>
          <doclet>org.jdrupes.mdoclet.MDoclet</doclet>
          <docletArtifacts>
            <docletArtifact>
              <groupId>org.jdrupes.mdoclet</groupId>
              <artifactId>doclet</artifactId>
              <version>3.1.0</version>
            </docletArtifact>
            <docletArtifact>
              <groupId>com.vladsch.flexmark</groupId>
              <artifactId>flexmark-all</artifactId>
              <version>0.64.0</version>   
            </docletArtifact>   
          </docletArtifacts>      
          
          <additionalDependencies>
          </additionalDependencies>
          <additionalJOptions>
            <additionalJOption>-J--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED</additionalJOption>
            <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</additionalJOption>
          </additionalJOptions>
        </configuration>
      </plugin>

@mnlipp maybe you can add this to the documentation. I think it will be helpful for many users/

**Comment by mnlipp** [comment]
@rmuller: Done.
