### ISSUE TITLE
warning: Error reading resource when using 4.0.0 (java 21)

### ISSUE THREAD

**Issue by rmuller** [mnlipp/jdrupes-mdoclet#22]
When using this doclet (4.0.0) with Java 21 a strange warning is shown:

`warning: Error reading resource: resources/releases/element-list-21.txt`

I assume this warning is generated by javadoc (message `doclet.Resource_error`, see https://github.com/openjdk/jdk21/blob/master/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/resources/standard.properties)

However, this file is not present in my code base and I suspect it comes from javadoc. I see https://github.com/openjdk/jdk21/tree/master/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/resources/releases
containing these kind of files, copied to your code base. I only cannot find element-list-21.txt. Maybe that is the problem?

**Comment by rmuller** [comment]
```
jmod list jdk.javadoc.jmod | grep '.txt'
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-10.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-11.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-12.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-13.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-14.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-15.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-16.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-17.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-18.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-19.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-20.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-21.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/element-list-9.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/package-list-7.txt
  classes/jdk/javadoc/internal/doclets/toolkit/resources/releases/package-list-8.txt
```

So i assume you have to add the `-21` one (every version has its own file)

**Comment by mnlipp** [comment]
The missing file is only in the jar distributed as part of the runtime. My guess is that it's generated (starting with Java-11) and added to the jar during built without being in the sources.

I attempted to not copy jdk.javadoc.internal.doclets.toolkit (as I'm patching only the html doclet), but again they have prevented reuse by checking at runtime that the toolkit classes are only used by the internal HTML doclet &mdash; crazy.

Assuming that despite the internal nature of all the APIs the mdoclet should and might work with some versions beyond Java-21, I've opted for loading the file using the classloader of `jdk.javadoc.internal.doclets.toolkit.AbstractDoclet` (instead of my copy's classloader). Of course, this requires yet another export/open.

**Comment by rmuller** [comment]
Thank you! I can confirm that it now works without any issues on a non-trivial multi-project running JDK 21.

The final maven configuration:

```
<additionalJOptions>
  <additionalJOption>-J--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED</additionalJOption>
  <additionalJOption>-J--add-exports=jdk.javadoc/jdk.javadoc.internal.doclets.toolkit=ALL-UNNAMED</additionalJOption>
  <additionalJOption>-J--add-opens=jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.resources.releases=ALL-UNNAMED</additionalJOption>            
  <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</additionalJOption>
  <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.doclint=ALL-UNNAMED</additionalJOption>
  <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</additionalJOption>
  <additionalJOption>-J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</additionalJOption>
</additionalJOptions>
```
