### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by delanym** [mnlipp/jdrupes-mdoclet#7]
Feature request: allow configuration of a favicon

**Comment by mnlipp** [comment]
Could you please elaborate on that? What's a favicon for a doclet? Where can it be seen?

**Comment by delanym** [comment]
This page suggests the doclet is the best place to configure a favicon https://stackoverflow.com/questions/13112123/creating-javadoc-html-pages-that-use-a-favicon

**Comment by mnlipp** [comment]
> This page suggests the doclet is the best place to configure a favicon https://stackoverflow.com/questions/13112123/creating-javadoc-html-pages-that-use-a-favicon

There' no mentioning of mdoclet on that page. I have no idea what you are referring to.

**Comment by delanym** [comment]
I get it: mdoclet is just a markdown preprocessor.
They mention customising the standard doclet. So if I make a custom doclet, how do I configure mdoclet to pass on to that doclet?

**Comment by mnlipp** [comment]
Okay, now I get what you meant.

mdoclet is a customization of the standard doclet. If you have another customization (such as handling a favicon) and you want to use both customizations together, the only way is to write a new doclet that combines both customizations (a kind of markdown-and-favicon-doclet).

I assume that the customization for supporting a favicon is not a big thing (especially compared to markdown support). So if you provide a pull request for adding this to mdoclet (which shouldn't be much different from adding it to the standard doclet), I can integrate the favocon customization in mdoclet.
