### ISSUE TITLE
Issue running with JDK11.0.10 on Windows OS

### ISSUE THREAD

**Issue by omkar07** [mnlipp/jdrupes-mdoclet#8]
Hi team, We are still getting issue on running it on Jdk11 though it works on jdk8. Below is our configuration:
**Configuration in pom.xml**
`          <configuration>
            
            <excludePackageNames>*.internal.*</excludePackageNames>
            <doclet>org.jdrupes.mdoclet.MDoclet</doclet>
            <docletArtifact>
              <groupId>org.jdrupes.mdoclet</groupId>
              <artifactId>doclet</artifactId>
              <version>1.0.10</version>
            </docletArtifact>
            <useStandardDocletOptions>true</useStandardDocletOptions>
            <aggregate>true</aggregate>
            <minmemory>256m</minmemory>
            <maxmemory>2048m</maxmemory>
            <additionalparam>-Xdoclint:none -disable-highlight</additionalparam>
            <sourcepath>target/generated-sources-for-docs/delombok</sourcepath>
            <links>
              <link>https://jax-rs-spec.java.net/nonav/2.0-rev-a/apidocs</link>
              <link>https://jersey.java.net/apidocs/${jersey.version}/jersey</link>
              <link>http://google.github.io/guava/releases/${guava.version}/api/docs</link>
            </links>
          </configuration>`
**Exception:**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (aggregate) on project oci-java-sdk-circuitbreaker: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages
[ERROR] com.sun.javadoc, com.sun.tools.doclets and their implementations
[ERROR] are planned to be removed in a future JDK release. These
[ERROR] components have been superseded by the new APIs in jdk.javadoc.doclet.
[ERROR] Users are strongly recommended to migrate to the new APIs.
[ERROR] javadoc: error - invalid flag: -Xdoclint:none
[ERROR] Command line was: C:\jdk-11.0.10\bin\javadoc.exe -J-Xmx2048m -J-Xms256m @options @argfile

**On removing Xdoclint param it gives below error**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (aggregate) on project oc
sdk-circuitbreaker: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages
[ERROR] com.sun.javadoc, com.sun.tools.doclets and their implementations
[ERROR] are planned to be removed in a future JDK release. These
[ERROR] components have been superseded by the new APIs in jdk.javadoc.doclet.
[ERROR] Users are strongly recommended to migrate to the new APIs.
[ERROR] javadoc: error - invalid flag: -bottom

**Comment by mnlipp** [comment]
I somehow doubt that you have configured version 2.0.0 of MDoclet as required for Java 11. Please try to extract the information about the doclet version being used from your logs.

**Comment by mnlipp** [comment]
Closed because no more information was supplied.
